### PR TITLE
printing out hex for binary in winreg hives

### PR DESCRIPTION
**Pull request by chb2mn**
## One line description of pull request

Changing binary output in winreg from summary of bytes to actual outputs.

## Description:

Analysts sometimes have the need to read the binary data in a registry value, so this changes binary to be output as hex.

### CODE REVIEW

**Comment by joachimmetz** [comment]
@chb2mn unfortunately this can lead to very large blobs, and this has been a deliberate decision not to print unknown binary data. Could you give me a bit more context about common cases you would like to be able to analyze. Should these be supported in another way, e.g. winreg plugin?

**Comment by chb2mn** [comment]
@joachimmetz I'll DM you use case stuff, as for a solution I was thinking some kind of config option, but a plugin might be sufficient

**Comment by joachimmetz** [comment]
Per side conversation getting to this as soon as https://github.com/log2timeline/plaso/issues/4700 is completed

**Comment by joachimmetz** [comment]
@chb2mn with https://github.com/log2timeline/plaso/pull/4715 merged let's discuss how to export the binary data in JSON. The built in serializer uses a type definition for this: https://github.com/log2timeline/plaso/blob/main/plaso/serializer/json_serializer.py#L76

**Comment by joachimmetz** [comment]
Per side conversation, closing this in favor of alternative approach

**Pull request closed without merging**
