### PR TITLE
Adds a Simple Docker Development Environment Guide

### PR DESCRIPTION
**Pull request by einfallstoll**
## One line description of pull request

Short guide to setup a Docker Development Environment.

## Description:

I wanted to work on the source code but needed a reliable and easy development environment. I thought Docker would be suitable for the requirements and I think others could use it as well.

## Checklist:
  - [x] Automated checks (Travis, Codecov, Codefactor )pass
  - [x] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
  - [ ] Reviewer assigned

### CODE REVIEW

**Comment by einfallstoll** [comment]
I didn't change any code, so the failing builds can be ignored, I guess.

**Comment by joachimmetz** [comment]
@einfallstoll thx for the changes, I'll rerun the AppVeyor tests see if the complete now.

**Comment by joachimmetz** [comment]
@Onager PTAL

**Comment by einfallstoll** [comment]
@Onager Thanks for the info. I didn't find this when I started working on Plaso. The script seems to do what I want with the difference that I don't rebuild the image every time rather than just install it in the container. IMHO this renders this pull request obsolete, and this indicates that maybe the documentation should be adjusted. What do you think?

**Comment by joachimmetz** [comment]
Closing per request reporter

**Pull request closed without merging**
