### PR TITLE
Unflatted JSON output

### PR DESCRIPTION
**Pull request by f-s-p**
The current JSON output contains flattened, string forms of other JSON objects.
Those objects also include flattened, string forms of additional objects.  This leads
to a large number of escape characters and ugly JSON.  This patch converts those
fields ('pathspec', and 'parent' within that) to dictionaries before converting the
whole thing to a JSON string for output.

### CODE REVIEW

**Comment by kiddinn** [comment]
could you go through this process for the code submit: http://plaso.kiddaland.net/developer/style-guide

since this is the official "plaso" way of submitting the code into the project.

**Comment by f-s-p** [comment]
Trying to submit using the utils/review.sh script, but getting a lint error on a line that I didn't change.  Should I try to make lint to ignore it since it is not connected to my changes, or should I try to fix it?
<pre>
************* Module plaso.output.json_out
C: 58, 0: Wrong continued indentation.
        basestring):
        ^                                     | (bad-continuation)
Fix linter errors before proceeding.
Upload aborted - fix the issues reported by the linter.
</pre>

**Comment by joachimmetz** [comment]
So you likely want to update with origin master first since the line you indicate does not make sense in the current version: https://github.com/log2timeline/plaso/blob/master/plaso/output/json_out.py#L58. Nor is there a reference of basestring currently in this file.

And yes you generally fix a linter error when you encounter it even if you did not introduce it yourself. Same with bugs, typos, and other things that need fixing.

**Comment by joachimmetz** [comment]
Since you did a github fork you'll have to set upstream yourself, since origin is your fork. See: https://github.com/log2timeline/plaso/wiki/Development-release-Ubuntu#update-frequently

**Comment by f-s-p** [comment]
My apologies, that was my mistake.  The lint error is on code that I added.  I'll fix and retry the utils/review.sh

**Comment by f-s-p** [comment]
Having trouble getting the run_tests script to be successful.  I have rolled back all of my changes so that I am just working with master and am getting a "Killed" error:
<pre>
testProcess (plaso.parsers.winreg_plugins.winrar_test.WinRarArcHistoryPluginTest)
Tests the Process function. ... ok
testParse (plaso.parsers.xchatlog_test.XChatLogUnitTest)
Tests the Parse function. ... WARNING:root:Unable to create timestamp from 2011-12-31 39:95:90.000000 with error: hour must be in 0..23
WARNING:root:Unknown locale header.
WARNING:root:Unknown locale header.
ok
testParse (plaso.parsers.skydrivelog_test.SkyDriveLogUnitTest)
Tests the Parse function. ... WARNING:root:Unable to create timestamp from 2013-13-33 21:28:46.742000 with error: month must be in 1..12
ok
testParse (plaso.parsers.bsm_test.MacOSXBsmParserTest)
Tests the Parse function on a Mac OS X BSM file. ... ok
testParse (plaso.parsers.bsm_test.OpenBsmParserTest)
Tests the Parse function on a "generic" BSM file. ... ok
testNtuserParsing (plaso.parsers.winreg_test.WinRegTest)
Parse a NTUSER.dat file and check few items. ... ERROR:root:Error in winreg/winreg_userassist while parsing file OS:/home/vagrant/plaso-github/test_data/NTUSER.DAT: Unsupported value data size: 8
ERROR:root:Error in winreg/winreg_userassist while parsing file OS:/home/vagrant/plaso-github/test_data/NTUSER.DAT: Unsupported value data size: 8
ERROR:root:Error in winreg/winreg_msie_zone while parsing file OS:/home/vagrant/plaso-github/test_data/NTUSER.DAT: Key: \Software\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones missing values.
ok
testSystemParsing (plaso.parsers.winreg_test.WinRegTest)
Parse a SYSTEM hive an run few tests. ... Killed
vagrant@vagrant-ubuntu-trusty-64:~/plaso-github$ git fetch
vagrant@vagrant-ubuntu-trusty-64:~/plaso-github$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
</pre>

I have built a fresh ubuntu/trusty64 vm (using Vagrant) and install all the packages mentioned in the Prepackaged Dependencies section of https://github.com/log2timeline/plaso/wiki/Dependencies---Ubuntu
I even tried installing everythting mentioned in the .travis.yml, since the Travis CI says that everything is fine for current master.  Nothing seems to be working.  Do you have a Vagrantfile or a prebuilt vm that I could use?  I would really like to contribute to this project.

**Comment by joachimmetz** [comment]
> Do you have a Vagrantfile or a prebuilt vm that I could use?

Alas not

> Having trouble getting the run_tests script to be successful. I have rolled back all of my changes so that I am just working with master and am getting a "Killed" error:

Can you be a bit more detailed, also see:

* https://github.com/log2timeline/plaso/wiki/Troubleshooting

Are your dependencies up to date? Also see:

* https://github.com/log2timeline/plaso/wiki/Development-release-Ubuntu
* https://github.com/log2timeline/plaso/wiki/Dependencies---Ubuntu

**Comment by joachimmetz** [comment]
Apparently I was not paying enough attention to your output
```
Parse a SYSTEM hive an run few tests. ... Killed
```

What happens if you run the test individually:
```
PYTHONPATH=. python plaso/parsers/winreg_test/py
```

**Comment by f-s-p** [comment]
I should have checked syslog.  It showed an out of memory error.  I increased the VM's memory to 2GB, and then ./run_tests.py ran just fine.  Thank you!  Will be submitting the utils/review.sh shortly.

**Comment by joachimmetz** [comment]
This PR might be obsolete after: https://codereview.appspot.com/229760043/ is submitted.

**Comment by joachimmetz** [comment]
The CL was submitted: https://github.com/log2timeline/plaso/commit/4774380df35a13ce2dfcbf270daf88c6ffadbcdc

**Pull request closed without merging**
