### PR TITLE
Compound ZIP parser plugin for Google Takeout

### PR DESCRIPTION
**Pull request by stefanomart**
## One line description of pull request
This is a PR about the Compound ZIP parser plugin for **Google Takeout** dump files.

## Description:
This plugin parses the Google Takeout dump. 
It parses these services:

- GMail
- Google Maps (location history)
- Google Chrome History
- My Activity
- Hangouts
- Purchases

I made a slight change to the czip logic: I added a method CheckZipFile to _czip_plugins\interface.py_ (this can be overrided by every czip plugin) to check the plugin: it checks if the zip file contains a file 'index.html' and the existence of the keyword 'Google Takeout' or 'Google Takeaway' in the same file.

Like we discussed [here](https://github.com/log2timeline/plaso/issues/2151), I added the logic of mailbox into plaso.

I hope that all the code styling rules are respected.

## Checklist:
  - [ ] Automated checks (Travis, Codecov, Codefactor )pass
  - [ ] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
  - [ ] Reviewer assigned

### CODE REVIEW

**Comment by stefanomart** [comment]
> Hey @stefanomart - I'm guessing this is still a work in progress. Please request a review from me once the test are passing - thanks!

Hi @Onager - I noticed that CodeFactor doesn't check the updated code, but checks always check the initial code (10 days ago).

**Comment by Onager** [comment]
OK @stefanomart  - pylint is passing in Travis, so I'll take a look.

**Comment by Onager** [comment]
Hey @stefanomart - there's no tests in this PR, could you please add a test for parser?

If you need test data, I noticed there's a public data set here: https://aboutdfir.com/dfir-research/ in the Android nougat image.

**Comment by stefanomart** [comment]
Hello again @Onager, I noticed that Travis could not complete due to an error: "Unable to locate package python3-tox". I also did not understand why CodeFactor still cheks old code (from 17 Jan).
However I added a test-data.
Thanks.

**Comment by stefanomart** [comment]
Even if I change the code, CodeFactor keeps to analyze the code uploaded on January 17th.
Am I doing something wrong?

**Comment by Onager** [comment]
Hey @stefanomart - don't worry too much about codefactor in this case, the extra pylint check will do most of the checks we'll need to work about.

**Comment by joachimmetz** [comment]
Closing no activity in a while

**Pull request closed without merging**
