### PR TITLE
CSV parser & M365 defender plugins

### PR DESCRIPTION
**Pull request by dafneb**
## One line description of pull request

CSV parser & M365 defender plugins

## Description:

Created new parser for CSV files, then created plugins which can process CSV export from Microsoft 365 Defender security portal. I recognised that those events could make timeline more accurate and give more interesting information's.  

What was done:
- new parser for CSV files
- new plugin for CSV parser - user's activity log
- new plugin for CSV parser - Advanced Hunting table DeviceEvents
- new plugin for CSV parser - Advanced Hunting table DeviceProcessEvents
- new plugin for CSV parser - Advanced Hunting table DeviceNetworkEvents
- new plugin for CSV parser - Advanced Hunting table DeviceImageLoadEvents
- new plugin for CSV parser - Advanced Hunting table DeviceFileEvents
- new plugin for CSV parser - Advanced Hunting table DeviceLogonEvents
- new plugin for CSV parser - Advanced Hunting table DeviceRegistryEvents
- new plugin for CSV parser - Advanced Hunting table UrlClickEvents
- additional tagging file for events
- unittests

## Notes:
All contributions to Plaso undergo [code review](https://github.com/log2timeline/l2tdocs/blob/main/process/Code%20review%20process.asciidoc).
This makes sure that the code has appropriate test coverage and conforms to the
[Plaso style guide](https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html).

One of the maintainers will examine your code, and may request changes. Check off the items below in
order, and then a maintainer will review your code.

## Checklist:
* [ ] Automated checks (GitHub Actions, AppVeyor) pass
* [ ] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
* [ ] Reviewer assigned

### CODE REVIEW

**Comment by joachimmetz** [comment]
One design question why create a new csv parser and not use the existing https://github.com/log2timeline/plaso/blob/main/plaso/parsers/dsv_parser.py ?

**Comment by dafneb** [comment]
Hi, reason is simple. I checked text parsers and so on, but just missed this one. Give me some time, I will try create another version and test this concrete parser and let's see if it will work.

**Comment by joachimmetz** [comment]
If they provide the same functionality let's use the existing one. We had various issues with CSV files in the past that the dsv parser accounts for.

**Comment by dafneb** [comment]
Hi @joachimmetz. 

I tested it and this dsv parser is working well with small modifications. So, I will re-arrange it and integrate these modifications inside my parsers. Then dsv parser will work normally and necessary changes will be only inside my inherited parsers.

**Comment by joachimmetz** [comment]
@dafneb did you intend to close this PR? are you planning to create a new PR? you could just keep this one and update it if you want.

**Comment by dafneb** [comment]
@joachimmetz Yes, there will be lots of changes on my side, so, I thought it will be better close this request, reset my branch (remove commits which will not be merged later on), make these changes and then create new PR. And I am still thinking which way will be better. 

Option 1) create separate parsers for each table (new 9 parsers)
Option 2) re-arrange my csv parser as inherited class of dsv parser and keep these plugins for each table. (new 1 parser + 9 plugins)

Looks like option 2 would be better choice ...

**Comment by joachimmetz** [comment]
Some context, plugins are original intended for container data formats that are used for different purposes (files), such as SQLite.

(I'll try to take a closer look maybe later) Based on a quick glance of your PR looks like you have 1 file https://github.com/log2timeline/plaso/pull/4782/files#diff-0c3efed10d32d011b06b71857e0fb5b7e9674cece7d8d1c6bf9e33504b4948c0 but different types of events. Closer to syslog (https://github.com/log2timeline/plaso/blob/main/plaso/parsers/text_plugins/syslog.py#L270), you could produce (emit) different event data objects for different types of log entries.

**Comment by dafneb** [comment]
Okay, looks like I found a way how to reduce number of parsers and so on. I will check it tonight.

**Pull request closed without merging**
