### PR TITLE
Additions to tag_linux.txt

### PR DESCRIPTION
**Pull request by pyllyukko**
## One line description of pull request

Additions to tag_linux.txt (#2762)

## Description:

* su & sudo failures
* Login failures due to nologin binary as shell
* Dovecot & Postfix logins & login fails
* sshd additions

## Notes:
All contributions to Plaso undergo [code
review](https://github.com/log2timeline/l2tdocs/blob/master/process/Code%20review%20process.asciidoc). This makes sure
that the code has appropriate test coverage and conforms to the Plaso [style
guide](https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html).

One of the maintainers will examine your code, and may request changes. Check off the items below in
order, and then a maintainer will review your code.

## Checklist:
  - [ ] Automated checks (Travis, Codecov, Codefactor )pass
  - [x] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
  - [ ] Reviewer assigned

### CODE REVIEW

**Comment by joachimmetz** [comment]
@pyllyukko thanks for the additions. Could you add some tests as well to https://github.com/log2timeline/plaso/blob/master/tests/data/tag_linux.py to ensure these rules remain working.

**Comment by pyllyukko** [comment]
> Could you add some tests as well to https://github.com/log2timeline/plaso/blob/master/tests/data/tag_linux.py to ensure these rules remain working.

I can try. How does that work? Should it be ran as part of [end-to-end tests](https://plaso.readthedocs.io/en/latest/sources/developer/Testing.html?highlight=tests#end-to-end-tests) (also I'm not seeing it in [end-to-end.ini](https://github.com/log2timeline/plaso/blob/master/config/end-to-end.ini))?

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/blob/master/tests/data/tag_linux.py are run as part of the unit tests. These test are mainly to safeguard tagging rules to be still working if event data changes.

**Comment by pyllyukko** [comment]
Gotcha! I'm on it.

**Comment by pyllyukko** [comment]
There (e9a1c2416fc061313c9da5721f5876c51bcb1f25). I hope I got them all covered. My eyes get crossed with so many almost identical lines.

**Comment by joachimmetz** [comment]
Thx, I'll have a close look at the test then.

If you have ideas on how to simplify writing the tests don't hesitate to let us know.

**Comment by pyllyukko** [comment]
Will do. Also I tried to model them after actual log lines as close as possible. I changed the `body contains 'uthentication fail'` for `sshd` from `'Authentication failure'` ([this](https://github.com/log2timeline/plaso/blob/4f17ed6ac1398e516d0aaca4a304d65bdcce0539/tests/data/tag_linux.py#L308)) => `authentication failure`, as that's how I see it in my logs. So this change from the original test(s) was intentional.

**Comment by joachimmetz** [comment]
@pyllyukko thx for the additions, this LGTM. I might have some idea to make it less tedious to write the tests https://github.com/log2timeline/plaso/issues/2937

**Pull request merged**
