### PR TITLE
Removed obsolete future dependency

### PR DESCRIPTION
**Pull request by thinrope**
## One line description of pull request
Remove obsolete future dependency

## Description:
In 2017 this dependency was added via https://github.com/log2timeline/plaso/pull/1335 for pefile, but after https://github.com/erocarrera/pefile/pull/349 merged in pefile-2023.2.7 it is not needed anymore. Also bump pefile minimum version.

## Notes:
All contributions to Plaso undergo [code review](https://github.com/log2timeline/l2tdocs/blob/main/process/Code%20review%20process.asciidoc).
This makes sure that the code has appropriate test coverage and conforms to the
[Plaso style guide](https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html).

One of the maintainers will examine your code, and may request changes. Check off the items below in
order, and then a maintainer will review your code.

## Checklist:
* [x] Automated checks (GitHub Actions, AppVeyor) pass
* [x] No new [new dependencies](https://plaso.readthedocs.io/en/latest/sources/developer/Adding-a-new-dependency.html) are required or l2tdevtools has been updated
* [x] Reviewer assigned

### CODE REVIEW

**Comment by joachimmetz** [comment]
Let's add a minimum version for pefile as well that removed future https://github.com/erocarrera/pefile/commit/36bf63f1185b8407ff9b4ce8c1c8e8620d8ae30f

**Comment by thinrope** [comment]
Looks like you added python3-dtfabric an hour ago to test_docker.yml ...

**Comment by joachimmetz** [comment]
@thinrope thanks for the proposed changes, be aware that github is warning about `This branch has conflicts that must be resolved`.

**Comment by joachimmetz** [comment]
assuming the PR got close by accident, I'll take another pass later

**Comment by thinrope** [comment]
Yes, I unintentionally closed it :-/
I should have created an issue and branch, instead of working directly on main in my fork; will do next time. I messed up while rebasing to your latest commits, so I resorted to `push --force` and github caught that and auto-closed it. I updated the description of the PR as well.

**Review by joachimmetz — APPROVED** [review]
LGTM

**Comment by joachimmetz** [comment]
> Yes, I unintentionally closed it :-/

No worries, just being explicit. Changes LGTM, thanks for making them

**Pull request merged**
