### PR TITLE
codespell check with several fixes

### PR DESCRIPTION
**Pull request by jaegeral**
codespell check of plaso project

### CODE REVIEW

**Comment by joachimmetz** [comment]
@jaegeral please resolve conflicts

**Review by joachimmetz — CHANGES_REQUESTED** [review]
Please resolve merge issues

**Comment by jaegeral** [comment]
ack, will resolve them next week

**Comment by joachimmetz** [comment]
@jaegeral could you please update this PR

**Comment by joachimmetz** [comment]
Looks like you fixed a typo that is actually in the source data:

```
Traceback (most recent call last):
  File "/__w/plaso/plaso/tests/parsers/asl.py", line 274, in testParse
    self.CheckEventValues(storage_writer, events[1], expected_event_values)
  File "./tests/parsers/test_lib.py", line 203, in CheckEventValues
    self.assertEqual(value, expected_value, error_message)
AssertionError: 'Inco[84 chars]l stop this compatiblity mapping behavior in the near future.' != 'Inco[84 chars]l stop this compatibility mapping behavior in the near future.'
- Incorrect NSStringEncoding value 0x8000100 detected. Assuming NSASCIIStringEncoding. Will stop this compatiblity mapping behavior in the near future.
+ Incorrect NSStringEncoding value 0x8000100 detected. Assuming NSASCIIStringEncoding. Will stop this compatibility mapping behavior in the near future.
?                                                                                                             +
 : event value: "message" does not match expected value
```

**Review by joachimmetz — CHANGES_REQUESTED** [review]
tests are failing, please fix

**Review by joachimmetz — APPROVED** [review]
LGTM

**Comment by joachimmetz** [comment]
@jaegeral I assume this PR was ready to be reviewed again now the tests pass?

**Pull request merged**
