### PR TITLE
Changes to tox Python 3.9 Travis CI test

### PR DESCRIPTION
**Pull request by joachimmetz**
Changes to tox Python 3.9 Travis CI test

To do:
* determine why 3.9 test is failing

### CODE REVIEW

**Review by rgayon — COMMENTED** [review]
It looks like libbde won't build with 3.9

**Comment by joachimmetz** [comment]
> It looks like libbde won't build with 3.9

For some reason it tries to build against Python 3.8

**Comment by rgayon** [comment]
The problem now is we need to build packages for Groovy

**Comment by joachimmetz** [comment]
> The problem now is we need to build packages for Groovy

Not necessarily this is a test that uses tox, that uses PyPI not the GIFT PPA

but my changes did not seem to do the trick, I'll marked this as blocked until I've figured out the root cause

**Comment by joachimmetz** [comment]
Since we're no longer using Travis CI I'll close this

**Pull request closed without merging**
