### PR TITLE
unify macOS data type.

### PR DESCRIPTION
**Pull request by aguilajesus**
unify macOS data type.

### CODE REVIEW

**Comment by aguilajesus** [comment]
part of #1628

**Comment by Onager** [comment]
This breaks compatibility - psort after this change won't be able to output from older storage files.  This isn't a huge problem, but there's no extra functionality added here, and this is mostly cosmetic.

I'd like to unify the data types at some point, but lets do it all at once, so we only break compatibility once.

**Comment by aguilajesus** [comment]
I see what you're saying, what about unifying the data types now and work a little bit the formatters to maintain compatibility with older storage files e.g.

```
class ApplicationUsageFormatter(interface.EventFormatter):
  """Formatter for a Macosx Application usage event."""
   DATA_TYPE = 'macosx:application_usage'


class MacOSApplicationUsageFormatter(ApplicationUsageFormatter):
  DATA_TYPE = 'macos:application_usage'
```

**Comment by aguilajesus** [comment]
per offline discussion, closing PR until we decide to break backward compatibility.

**Pull request closed without merging**
